-- SPRINT-041: storage usage tracking.
-- Adds a generated byte_size column to vault_files so per-user storage can
-- be aggregated without reading content. OCTET_LENGTH gives actual UTF-8
-- byte count (accurate for multi-byte characters) vs LENGTH which counts
-- code points. This column also serves as the foundation for image storage
-- accounting once that tier ships (image rows will carry explicit byte_size
-- values since their content field will hold a storage key, not the bytes).

ALTER TABLE public.vault_files
  ADD COLUMN IF NOT EXISTS byte_size INT
    GENERATED ALWAYS AS (OCTET_LENGTH(COALESCE(content, ''))) STORED;

-- Covering index so the admin aggregate and per-user usage query never
-- touch the content column.
CREATE INDEX IF NOT EXISTS vault_files_ns_bytes_idx
  ON public.vault_files (namespace, byte_size);

-- Per-namespace aggregate view used by the admin storage page.
-- Returns one row per namespace — safe to query without pagination as long
-- as the number of distinct namespaces stays under 1000 (safe for current scale).
CREATE OR REPLACE VIEW public.vault_storage_by_namespace AS
  SELECT
    namespace,
    COUNT(*)::BIGINT            AS doc_count,
    COALESCE(SUM(byte_size), 0)::BIGINT AS bytes_used,
    MAX(updated_at)             AS last_write
  FROM public.vault_files
  GROUP BY namespace;

-- RPC for a single user's own storage stats (called by /api/usage).
-- SECURITY DEFINER so the anon/authed role can call it without direct
-- access to vault_files (which is service-role only).
CREATE OR REPLACE FUNCTION public.vault_storage_for_namespace(p_namespace TEXT)
RETURNS TABLE(doc_count BIGINT, bytes_used BIGINT, last_write TIMESTAMPTZ)
LANGUAGE SQL STABLE SECURITY DEFINER AS $$
  SELECT doc_count, bytes_used, last_write
  FROM public.vault_storage_by_namespace
  WHERE namespace = p_namespace;
$$;
